spring:
  application:
    name: MyBatis-Project
  datasource:
    # 配置数据库
    url: jdbc:mysql://localhost:3306/hxl
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # 切换连接池为druid
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    #MyBatix日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # log-prefix: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置XML映射文件位置
  mapper-locations: classpath:mapper/*.xml


