spring:
    application:
        name: demo
    jmx:
        enabled: true
management:
    endpoints:
        web:
            exposure:
                include: beans
        jmx:
            exposure:
                include: beans